### Numpy ndarray 개요

In [3]:
import numpy as np #패키지 import

In [4]:
array1 = np.array([1,2,3]) # array함수를 통해 1차원 배열 생성
print('array1 type:',type(array1)) # 자료형을 출력 
print('array1 array 형태:',array1.shape) # shape라는 튜플은 배결의 각 차원의 크기를 알려준다. 

array2 = np.array([[1,2,3], 
                  [2,3,4]]) # array함수를 통해 2차원 배열 생성
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
# ndarray.ndim을 통해 ndarray의 차원을 알 수 있다. 


array1: 1차원, array2: 2차원, array3:  2차원


In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # ndarray.dtype을 통해서 ndarray 내의 데이터 타입을 확인
# type을 통해 데이터의 타입을 확인한다. 이때, ndarray 내 데이터 타입은 같은 종류의 데이터만 담을 수 있다. 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# 서로 다른 타입의 데이터가 들어있는 배열을 출력해보니, 하나의 타입으로 통일되어 출력된다.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

# 숫자형의 경우 int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit),
#float형(16bit, 32bit, 64bit, 128bit) 타입도 제공한다. 


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# np.arange는 range와는 달리 ndarray 형태로 모든 값을 생성한다.

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [10]:
zero_array = np.zeros((3,2),dtype='int32') # zeros를 통해 값이 모두 0인 배열 생성한다.  
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # ones를 통해 값이 모두 1인 배열 생성한다.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [12]:
array1 = np.arange(10) # 1부터 10까지의 모든 값을 가지는 배열을 생성했다. 
print('array1:\n', array1)

array2 = array1.reshape(2,5) #이를 2차원의 2*5 ndarray로 전환했다.
print('array2:\n',array2)

array3 = array1.reshape(5,2) # 5*2 ndarray로 전환했다.
print('array3:\n',array3)
# reshape는 ndarray를 특정 차원 및 형태로 변화하며, 변환 형태를 함수 인자로 부여하면 된다.

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1.reshape(4,3) # 변환되는 array의 크기(element의 개수)가 같지 않기 때문에 reshape가 불가능하다. 

ValueError: cannot reshape array of size 10 into shape (4,3)

In [18]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) 
print('array2 shape:',array2.shape)
# -1은 row에 맞춰서 column개수를 맞추는 것을 의미한다. 
# 여기서는 고정된 5개의 column axis크기에 맞는 row axis크기를 자동으로 생성해 변환한다. 
# 즉, shape는 (2,5)이다.

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
# 여기서는 고정된 5개의 row axis크기에 맞는 column axis크기를 자동으로 생성해 변환한다. 
# 즉, shape는 (5,2)이다.

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [19]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)
# 여기서는 고정된 4개의 column axis크기에 맞는 row axis크기를 자동으로 생성해 변환할 수 없으므로 reshape가 불가능하다.. 

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 1에서 8까지의 수를 총 element의 수가 같게 reshape한다.
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) # 2차원으로 변환하되 column axis크기가 1로 고정된다.
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [20]:
# 1에서 부터 9 까지의 1차원 ndarray 생성한다.
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미한다.
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [22]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])
# '-'는 뒤에서부터를 의미한다.

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [24]:
array1[0] = 9 # 첫 번째 값을 '9'로 할당했다.
array1[8] = 0 # 아홉 번째 값을 '0'으로 할당했다.
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10)# 1에서 부터 10 까지의 1차원 ndarray 생성한다.
array2d = array1d.reshape(3,3) #2차원으로 변환한다. 
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )
#array[row의 인덱스값, column의 인덱스값]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [25]:
array1 = np.arange(start=1, stop=10) # 1에서 부터 10 까지의 1차원 ndarray 생성한다.
array3 = array1[0:3] # 슬라이싱은 :을 이용하여 연속된 값을 선택한다.
# 여기서는 첫 번째부터 세 번째 값까지를 의미한다
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:] # 인덱스 값을 입력하지 않으면 제일 처음과 마지막까지의 값을 의미한다. 
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [32]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3차원으로 변환한다. 
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
# 첫 번째에서 두 번째 row의 값을 첫 번째, 두 번째 column에서 출력한다. 
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
# 두 번째에서 세 번째 row의 값을 첫 번째에서  세 번째 column에서 출력한다. 
print('array2d[1:3, :] \n', array2d[1:3, :])
# 두 번째에서 세 번째 row의 값을 전체 column에서 출력한다. 
print('array2d[:, :] \n', array2d[:, :])
# 전체 dnarray를 출력한다.
print('array2d[:2, 1:] \n', array2d[:2, 1:])
#첫 번째에서 두 번째 row의 값을 두 번째에서  세 번째 column에서 출력한다. 
print('array2d[:2, 0] \n', array2d[:2, 0])
#첫 번째에서 두 번째 row의 값을 첫 번째 column에서 출력한다. 

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [29]:
print(array2d[0]) # row의 인덱스 값이 0인 것을 출력한다.
print(array2d[1]) # row의 인덱스 값이 1인 것을 출력한다.
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [35]:
# 팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 저장하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱스 방식이다. 
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())
# 첫 번째와 두 번째 row에 있는 값중 세 번째 column에 있는 값을 출력한다.

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())
# 첫 번째와 두 번째 row에 있는 값중 첫 번째에서 두 번째 column에 있는 값을 출력한다.

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())
# 첫 번째와 두 번째 row에 있는 값중 전체 column에 있는 값을 출력한다.

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [36]:
# 불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방식이다.
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5] # ndarray내의 값 중 5보다 큰 dnarray를 출력
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [37]:
array1d > 5
# 불린 인덱싱에서는 조건에 맞는 값은 True로 나오고, 이에 해당하는 인덱스 값만 저장한다. 

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [4]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
# 원 행렬은 그대로 유지한 채 원 행렬 내 원소를 기본적으로 오름차순으로 정렬하여 반환한다.
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [5]:
sort_array1_desc = np.sort(org_array)[::-1] # 내림차순으로 정렬한다.
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [6]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)
# 2차원 배열에서 axis=0dms row방향, axis=1은 colmn방향으로 정렬한다.

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [7]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices) # 기본적으로 오름차순이기 때문이 값이 작은 것부터 인덱싱된다.

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [8]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] #내림차순으로 정렬
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc) #내림차순으로 정렬하므로 값이 큰 것부터 인덱싱된다.

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [9]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])# 성적 배열의 인덱스를 활용하여 이름을 출력한다.

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)
# 58 = 1*7 + 2*9 + 3*11
# 64 = 1*8 + 2*10 + 3*12
#139 = 4*7 + 5*9 + 6*11
#154 = 4*8 + 5* 10 + 6*12

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
